language: python
python:
- '3.6'
services: mongodb
before_install:
- pip install pytest pytest-cov
- pip install codecov
install:
- pip install -r requirements.txt --quiet
script:
- py.test --cov flask_user --cov-report term-missing --cov-config flask_user/tests/.coveragerc
  flask_user/tests
after_success:
- codecov
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: OrNBf7q5rL1A/JQV8HtwZpy2TMXlZKAufpdhROfMpuisSdsLckMwfTDo45JXiSS2LRKJftLR8d1twxauGY75WzfNBRMcMzybB6k3jGnWaE3kaH8cdqoPfkxtggctyfiV/lVx6+aGRfTdGK3KXtwG/ICbXsPotI+3NvATnH0SQ1IAV9U5PKEI0RNa0f2CofRv5oPpAWLT2Ji0gf9nYPyeVbkAColF7024XkKkhX6I8K+D5B92C5Gitf0FL/cToFz+JFo/9k6SuMEsSz76IAbZR+YiITgC8Y1WEZ+Pa4cNbBR19Uf2m/jMI+FJMU50QywrAu6AvUnwk3OuxTMmJv6HigsSQ0CT9Nt5pUochkUN4wr1lkcedSf4HvvYYfsEZ1lZaDLH+jfot/5GDPS26ylTixYRrLz0jmb53Mb0LiMW0KZpFa5U4FmuZeSGlFsRy/XRUYBeGTRCAa/tgXSNq7h3uW9MvW1rUkmGLFhpqczcUdCrz1ZmtrsBV2iDinB5fy0qXj13oiafEeW6fByZuRPFI20FJwbURblJ2WbvHQeuHlWXGlDAEO9ZMRoKzbAUaGhY+sbV9NL4nj07GhXFc7Pt9J4bykVD/qoDybLZ2YS6oTW9t9tkjvCL4YuAuRGc1HZ44bqjF+edLE5Y4kUMLHkjj7G+xYnGJ+FcUObVhYsQf24=
